In [3]:
# Import Libraries

import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
# Load Cleaned Dataset

df = pd.read_csv(r"D:\New Sprint\dataset\processed\cleaned_data.csv")

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [5]:
# Encode Gender Column

gender_encoder = LabelEncoder()

df["gender"] = gender_encoder.fit_transform(df["gender"])

print(df["gender"].head())

0    0
1    0
2    1
3    0
4    1
Name: gender, dtype: int64

In [6]:
# Encode Smoking History Column

smoking_encoder = LabelEncoder()

df["smoking_history"] = smoking_encoder.fit_transform(df["smoking_history"])

print(df["smoking_history"].head())

0    4
1    0
2    4
3    1
4    1
Name: smoking_history, dtype: int64

In [7]:
# Create BMI Category Feature

df["bmi_category"] = pd.cut(
    df["bmi"],
    bins=[0, 18.5, 25, 30, 100],
    labels=[0, 1, 2, 3]
)

print(df["bmi_category"].head())

0    2
1    2
2    2
3    1
4    1
Name: bmi_category, dtype: category
Categories (4, int64): [0 < 1 < 2 < 3]

In [8]:
# Convert BMI Category to Integer

df["bmi_category"] = df["bmi_category"].astype(int)

In [9]:
# Create Glucose Risk Feature

df["glucose_risk"] = df["blood_glucose_level"].apply(
    lambda x: 1 if x > 140 else 0
)

print(df["glucose_risk"].head())

0    0
1    0
2    1
3    1
4    1
Name: glucose_risk, dtype: int64

In [10]:
# Check Final Dataset

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_category,glucose_risk
0,0,80.0,0,1,4,25.19,6.6,140,0,2,0
1,0,54.0,0,0,0,27.32,6.6,80,0,2,0
2,1,28.0,0,0,4,27.32,5.7,158,0,2,1
3,0,36.0,0,0,1,23.45,5.0,155,0,1,1
4,1,76.0,1,1,1,20.14,4.8,155,0,1,1

In [11]:
# Save Engineered Dataset

df.to_csv(
    r"D:\New Sprint\dataset\processed\engineered_data.csv",
    index=False
)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!