In [18]:
# Import Libraries

import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [2]:
# Load Feature Engineered Dataset

df = pd.read_csv(r"D:\New Sprint\dataset\processed\engineered_data.csv")

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_category,glucose_risk
0,0,80.0,0,1,4,25.19,6.6,140,0,2,0
1,0,54.0,0,0,0,27.32,6.6,80,0,2,0
2,1,28.0,0,0,4,27.32,5.7,158,0,2,1
3,0,36.0,0,0,1,23.45,5.0,155,0,1,1
4,1,76.0,1,1,1,20.14,4.8,155,0,1,1

In [3]:
# Features and Target

X = df.drop("diabetes", axis=1)

y = df["diabetes"]

print(X.shape)
print(y.shape)

(96012, 10)
(96012,)

In [4]:
# Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (76809, 10)
Testing Shape: (19203, 10)

In [5]:
# Train Random Forest Model

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Training Completed!")

Model Training Completed!

In [6]:
# Training Accuracy

train_predictions = model.predict(X_train)

train_accuracy = accuracy_score(y_train, train_predictions)

print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.9991797836191071

In [7]:
# Testing Accuracy

test_predictions = model.predict(X_test)

test_accuracy = accuracy_score(y_test, test_predictions)

print("Testing Accuracy:", test_accuracy)

Testing Accuracy: 0.9693277092121023

In [8]:
# Classification Report

print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98     17490
           1       0.94      0.70      0.80      1713

    accuracy                           0.97     19203
   macro avg       0.96      0.85      0.89     19203
weighted avg       0.97      0.97      0.97     19203

In [9]:
# Confusion Matrix

cm = confusion_matrix(y_test, test_predictions)

print(cm)

[[17418    72]
 [  517  1196]]

In [ ]:
# Save Model using Pickle

with open(r"D:\New Sprint\ml\diabetes_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model Saved Successfully!")

Model Saved Successfully!

In [19]:
# Create encoders

gender_encoder = LabelEncoder()

smoking_encoder = LabelEncoder()

# Encode columns

df["gender"] = gender_encoder.fit_transform(
    df["gender"]
)

df["smoking_history"] = smoking_encoder.fit_transform(
    df["smoking_history"]
)

# Display encoded dataset

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,bmi_category,glucose_risk
0,0,80.0,0,1,4,25.19,6.6,140,0,2,0
1,0,54.0,0,0,0,27.32,6.6,80,0,2,0
2,1,28.0,0,0,4,27.32,5.7,158,0,2,1
3,0,36.0,0,0,1,23.45,5.0,155,0,1,1
4,1,76.0,1,1,1,20.14,4.8,155,0,1,1

In [ ]:
import pickle

# Save gender encoder

with open(r"D:\New Sprint\ml\gender_encoder.pkl", "wb") as file:
    pickle.dump(gender_encoder, file)

# Save smoking encoder

with open(r"D:\New Sprint\ml\smoking_encoder.pkl", "wb") as file:
    pickle.dump(smoking_encoder, file)

print("Encoders saved successfully!")

Encoders saved successfully!

In [ ]:
# Load saved encoder

with open(r"D:\New Sprint\ml\gender_encoder.pkl", "rb") as file:
    loaded_gender_encoder = pickle.load(file)

print("Encoder loaded successfully!")

Encoder loaded successfully!